services:
  nest:
    image: ghcr.io/jadenyun/converter:latest
    container_name: nest-app
    restart: unless-stopped
    ports:
      - "3002:3002"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge